import type { Metadata } from "next";
import { Geist, Geist_Mono, Unbounded, Prompt } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const unbounded = Unbounded({
  subsets: ['latin'], // หรือ ['thai', 'latin'] ถ้าฟอนต์รองรับไทย
  weight: ['400', '700'], // เลือกน้ำหนักที่ใช้
  display: 'swap',
  variable: '--font-Unbounded', // ใช้ร่วมกับ Tailwind CSS
}) 

const prompt = Prompt({
  subsets: ['thai', 'latin'], // หรือ ['thai', 'latin'] ถ้าฟอนต์รองรับไทย
  weight: ['200','400','600'], // เลือกน้ำหนักที่ใช้
  display: 'swap',
  variable: '--font-prompt', // ใช้ร่วมกับ Tailwind CSS
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${unbounded.variable} ${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
